name: CI - SNPE Flask App (Ubuntu 24.04)

on:
  push:
    branches: [ "24.04" ]
  pull_request:
    branches: [ "24.04" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image using docker-compose
      - name: Build Docker image
        run: docker compose -f Tutorials/docker-compose.yml build snpe-flask

      #4. Stop and remove containers
      - name: Clean up
        run: docker compose -f Tutorials/docker-compose.yml down
